### ISSUE TITLE
Add "formURL" and "requestsURL" in Process Metadata details

### ISSUE THREAD

**Issue by emmdim** [vocdoni/dvote-js#12]
"formURL": Base64 encoded string generated by the fields titles of the form csv. It is used also as the identifier of the login page (login/${formURI}) "requestsURL": URL that is defined in create process and appears in the webpoll pointing to Questionaire (survey/Questions and Answers) of the organization

**Comment by brickpop** [comment]
An option could be to add a `meta` field on the process metadata.

This field would allow for using arbitrary key/value strings, and this would enable specific use cases to have their own custom fields without polluting the schema of the rest of governance processes. 

It would be nice that even if specific, these custom fields were specified as well.

**Comment by elboletaire** [comment]
Let's add that `meta` field to allow arbitrary key values for two reasons:

- These keys are very specific to the manager and the webpoll. The app probably won't use any of these, so they don't need to be a standard of the process params definition.
- There's a mid-long term change to how metadata works with something called "blocks", so it doesn't make much of a sense to be adding key by key new stuff, if this is gonna change.

**Comment by brickpop** [comment]
Added in https://github.com/vocdoni/dvote-js/commit/04c88cf4fdef23917a3180762fa9927a37c058b8

dvote-js@v0.20.1 is live
