### ISSUE TITLE
Adapt for v1 of Payment Smart Contracts

### ISSUE THREAD

**Issue by emmdim** [vocdoni/dvote-js#28]
* [ ] Implement `getProcessPrice`
* [ ] support sending ether during `createVotingProcess`

Blocked by:  https://github.com/vocdoni/dvote-solidity/pull/15

**Comment by brickpop** [comment]
vocdoni/dvote-solidity#15 has been merged

**Comment by brickpop** [comment]
And https://github.com/vocdoni/dvote-js/commit/8252d8c7be2c69cc116a792d6a87c80e88083b9e is landed

- `getProcessPrice` is now available on `VotingApi`
- `newProcess` automatically sets the `value` to the current price, so that the user only needs to accept the transaction
